apiVersion: 1
datasources:
  - name: ClickHouse (SigNoz)
    type: grafana-clickhouse-datasource
    uid: clickhouse-signoz
    access: proxy
    isDefault: true
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      defaultDatabase: signoz_traces
    editable: false
